INSERT INTO state(id, state, uf) VALUES (1, 'ALagoas', 'AL');

Insert into city (city, state_id) values ('Água Branca', 1);
Insert into city (city, state_id) values ('Anadia', 1);
Insert into city (city, state_id) values ('Arapiraca', 1);
Insert into city (city, state_id) values  ('Atalaia', 1);
Insert into city (city, state_id) values  ('Barra de Santo Antônio', 1);
Insert into city (city, state_id) values  ('Barra de São Miguel', 1);
Insert into city (city, state_id) values  ('Batalha', 1);
Insert into city (city, state_id) values  ('Belém', 1);
Insert into city (city, state_id) values  ('Belo Monte', 1);
Insert into city (city, state_id) values  ('Boca da Mata', 1);
Insert into city (city, state_id) values  ('Branquinha', 1);
Insert into city (city, state_id) values  ('Cacimbinhas', 1);
Insert into city (city, state_id) values  ('Cajueiro', 1);
Insert into city (city, state_id) values  ('Campestre', 1);
Insert into city (city, state_id) values  ('Campo Alegre', 1);
Insert into city (city, state_id) values  ('Campo Grande', 1);
Insert into city (city, state_id) values  ('Canapi', 1);
Insert into city (city, state_id) values  ('Capela', 1);
Insert into city (city, state_id) values  ('Carneiros', 1);
Insert into city (city, state_id) values  ('Chã Preta', 1);
Insert into city (city, state_id) values  ('Coité do Nóia', 1);
Insert into city (city, state_id) values  ('Colônia Leopoldina', 1);
Insert into city (city, state_id) values  ('Coqueiro Seco', 1);
Insert into city (city, state_id) values  ('Coruripe', 1);
Insert into city (city, state_id) values  ('Craíbas', 1);
Insert into city (city, state_id) values  ('Delmiro Gouveia', 1);
Insert into city (city, state_id) values  ('Dois Riachos', 1);
Insert into city (city, state_id) values  ('Estrela de Alagoas', 1);
Insert into city (city, state_id) values  ('Feira Grande', 1);
Insert into city (city, state_id) values  ('Feliz Deserto', 1);
Insert into city (city, state_id) values  ('Flexeiras', 1);
Insert into city (city, state_id) values  ('Girau do Ponciano', 1);
Insert into city (city, state_id) values  ('Ibateguara', 1);
Insert into city (city, state_id) values  ('Igaci', 1);
Insert into city (city, state_id) values  ('Igreja Nova', 1);
Insert into city (city, state_id) values  ('Inhapi', 1);
Insert into city (city, state_id) values  ('Jacaré dos Homens', 1);
Insert into city (city, state_id) values  ('Jacuípe', 1);
Insert into city (city, state_id) values  ('Japaratinga', 1);
Insert into city (city, state_id) values  ('Jaramataia', 1);
Insert into city (city, state_id) values  ('Jequiá da Praia', 1);
Insert into city (city, state_id) values  ('Joaquim Gomes', 1);
Insert into city (city, state_id) values  ('Jundiá', 1);
Insert into city (city, state_id) values  ('Junqueiro', 1);
Insert into city (city, state_id) values  ('Lagoa da Canoa', 1);
Insert into city (city, state_id) values  ('Limoeiro de Anadia', 1);
Insert into city (city, state_id) values  ('Maceió', 1);
Insert into city (city, state_id) values  ('Major Isidoro', 1);
Insert into city (city, state_id) values  ('Maragogi', 1);
Insert into city (city, state_id) values  ('Maravilha', 1);
Insert into city (city, state_id) values  ('Marechal Deodoro', 1);
Insert into city (city, state_id) values  ('Maribondo', 1);
Insert into city (city, state_id) values  ('Mar Vermelho', 1);
Insert into city (city, state_id) values  ('Mata Grande', 1);
Insert into city (city, state_id) values  ('Matriz de Camaragibe', 1);
Insert into city (city, state_id) values  ('Messias', 1);
Insert into city (city, state_id) values  ('Minador do Negrão', 1);
Insert into city (city, state_id) values  ('Monteirópolis', 1);
Insert into city (city, state_id) values  ('Murici', 1);
Insert into city (city, state_id) values  ('Novo Lino', 1);
Insert into city (city, state_id) values  ('Olho D''Água das Flores', 1);
Insert into city (city, state_id) values  ('Olho D''Água do Casado', 1);
Insert into city (city, state_id) values  ('Olho D''Água Grande', 1);
Insert into city (city, state_id) values  ('Olivença', 1);
Insert into city (city, state_id) values  ('Ouro Branco', 1);
Insert into city (city, state_id) values  ('Palestina', 1);
Insert into city (city, state_id) values  ('Palmeira dos Índios', 1);
Insert into city (city, state_id) values  ('Pão de Açúcar', 1);
Insert into city (city, state_id) values  ('Pariconha', 1);
Insert into city (city, state_id) values  ('Paripueira', 1);
Insert into city (city, state_id) values  ('Passo de Camaragibe', 1);
Insert into city (city, state_id) values  ('Paulo Jacinto', 1);
Insert into city (city, state_id) values  ('Penedo', 1);
Insert into city (city, state_id) values  ('Piaçabuçu', 1);
Insert into city (city, state_id) values  ('Pilar', 1);
Insert into city (city, state_id) values  ('Pindoba', 1);
Insert into city (city, state_id) values  ('Piranhas', 1);
Insert into city (city, state_id) values  ('Poço das Trincheiras', 1);
Insert into city (city, state_id) values  ('Porto Calvo', 1);
Insert into city (city, state_id) values  ('Porto de Pedras', 1);
Insert into city (city, state_id) values  ('Porto Real do Colégio', 1);
Insert into city (city, state_id) values  ('Quebrangulo', 1);
Insert into city (city, state_id) values  ('Rio Largo', 1);
Insert into city (city, state_id) values  ('Roteiro', 1);
Insert into city (city, state_id) values  ('Santa Luzia do Norte', 1);
Insert into city (city, state_id) values  ('Santana do Ipanema', 1);
Insert into city (city, state_id) values  ('Santana do Mundaú', 1);
Insert into city (city, state_id) values  ('São Brás', 1);
Insert into city (city, state_id) values  ('São José da Laje', 1);
Insert into city (city, state_id) values  ('São José da Tapera', 1);
Insert into city (city, state_id) values  ('São Luís do Quitunde', 1);
Insert into city (city, state_id) values  ('São Miguel dos Campos', 1);
Insert into city (city, state_id) values  ('São Miguel dos Milagres', 1);
Insert into city (city, state_id) values  ('São Sebastião', 1);
Insert into city (city, state_id) values  ('Satuba', 1);
Insert into city (city, state_id) values  ('Senador Rui Palmeira', 1);
Insert into city (city, state_id) values  ('Tanque D''Arca', 1);
Insert into city (city, state_id) values  ('Taquarana', 1);
Insert into city (city, state_id) values  ('Teotônio Vilela', 1);
Insert into city (city, state_id) values  ('Traipu', 1);
Insert into city (city, state_id) values  ('União dos Palmares', 1);
Insert into city (city, state_id) values  ('Viçosa', 1);
